-- MySQL Script generated by MySQL Workbench
-- Sat Sep  6 21:14:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MundoGPUBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MundoGPUBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MundoGPUBD` DEFAULT CHARACTER SET utf8mb3 ;
USE `MundoGPUBD` ;

-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Generales` (
  `idGeneral` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  PRIMARY KEY (`idGeneral`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`user` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` ENUM('ENCARGADO', 'ADMIN', 'EMPLEADO') NOT NULL,
  `Generales_idGeneral` INT NOT NULL,
  PRIMARY KEY (`idUSER`),
  INDEX `fk_user_Generales_idx` (`Generales_idGeneral` ASC) VISIBLE,
  CONSTRAINT `fk_user_Generales`
    FOREIGN KEY (`Generales_idGeneral`)
    REFERENCES `MundoGPUBD`.`Generales` (`idGeneral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;

CREATE TABLE IF NOT EXISTS GPUs (
    Id INT NOT NULL AUTO_INCREMENT,
    Marca VARCHAR(50) NOT NULL,
    Modelo VARCHAR(100) NOT NULL,
    VRAM VARCHAR(50) NOT NULL,
    NucleosCuda INT NOT NULL,
    RayTracing TINYINT(1) NOT NULL,
    Imagen VARCHAR(255),
    Precio DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (Id)
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
