-- MySQL Script generated by MySQL Workbench
-- Sun Sep  7 14:49:31 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MundoGPUBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MundoGPUBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MundoGPUBD` DEFAULT CHARACTER SET utf8mb3 ;
USE `MundoGPUBD` ;

-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Nivel_Academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Nivel_Academico` (
  `idNivel` INT NOT NULL AUTO_INCREMENT,
  `Nivel` VARCHAR(50) NOT NULL,
  `Institucion` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idNivel`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Generales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Generales` (
  `idGeneral` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `sexo` ENUM('M', 'F') NOT NULL,
  `Nivel_Academico_idNivel` INT NOT NULL,
  PRIMARY KEY (`idGeneral`),
  INDEX `fk_Generales_Nivel_Academico1_idx` (`Nivel_Academico_idNivel` ASC) VISIBLE,
  CONSTRAINT `fk_Generales_Nivel_Academico1`
    FOREIGN KEY (`Nivel_Academico_idNivel`)
    REFERENCES `MundoGPUBD`.`Nivel_Academico` (`idNivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`user` (
  `idUSER` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `rol` ENUM('ADMIN', 'ENCARGADO', 'EMPLEADO') NOT NULL,
  `Generales_idGeneral` INT NOT NULL,
  PRIMARY KEY (`idUSER`),
  UNIQUE INDEX `UC_User_Username` (`username` ASC) VISIBLE,
  INDEX `fk_user_Generales_idx` (`Generales_idGeneral` ASC) VISIBLE,
  CONSTRAINT `fk_user_Generales`
    FOREIGN KEY (`Generales_idGeneral`)
    REFERENCES `MundoGPUBD`.`Generales` (`idGeneral`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`Proveedores` (
  `idProveedor` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NOT NULL,
  `Direccion` VARCHAR(255) NULL DEFAULT NULL,
  `Telefono` VARCHAR(20) NULL DEFAULT NULL,
  `Email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`idProveedor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `MundoGPUBD`.`GPU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MundoGPUBD`.`GPU` (
  `idGPU` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(50) NOT NULL,
  `Modelo` VARCHAR(100) NOT NULL,
  `VRAM` VARCHAR(50) NOT NULL,
  `NucleosCuda` INT NOT NULL,
  `RayTracing` TINYINT(1) NOT NULL,
  `Imagen` VARCHAR(255) NOT NULL,
  `Precio` DECIMAL(10,2) NOT NULL,
  `Proveedores_idProveedor` INT NOT NULL,
  PRIMARY KEY (`idGPU`),
  INDEX `fk_GPU_Proveedores1_idx` (`Proveedores_idProveedor` ASC) VISIBLE,
  CONSTRAINT `fk_GPU_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedor`)
    REFERENCES `MundoGPUBD`.`Proveedores` (`idProveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

-- 1️⃣ Insertar un nivel académico para el admin
INSERT INTO Nivel_Academico (Nivel, Institucion)
VALUES ('Licenciatura', 'Universidad Nacional');

-- Obtener el último idNivel insertado
SET @idNivelAdmin = LAST_INSERT_ID();

-- 2️⃣ Insertar los datos generales del admin
INSERT INTO Generales (nombre, apellido, sexo, Nivel_Academico_idNivel)
VALUES ('Admin', 'Admin', 'M', @idNivelAdmin);

-- Obtener el último idGeneral insertado
SET @idGeneralAdmin = LAST_INSERT_ID();

-- 3️⃣ Insertar el usuario admin
INSERT INTO user (username, password, rol, Generales_idGeneral)
VALUES ('Admin', 'Admin', 'ADMIN', @idGeneralAdmin);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
